### PR TITLE
Implement testing multiple versions

### LINKED ISSUE #1: Support for EAP versions
Add support for e.g. `LATEST-EAP-VERSION` instead of manually specifying a version number.

Inspire by https://github.com/JetBrains/gradle-intellij-plugin/blob/48e728aa7d94206fb9233103261643e6cef262a7/src/main/groovy/org/jetbrains/intellij/Utils.groovy#L196

### PR DESCRIPTION
**Pull request by thepieterdc**
Requested by @hsz.

### CODE REVIEW

**Comment by hsz** [comment]
Did I really make such request?

**Comment by thepieterdc** [comment]
@hsz my bad I tagged the wrong person, Yann from JB sent me an email and I saw you were in the stargazers list but didn't check the name :p

**Comment by YannCebron** [comment]
Thanks :)

**Comment by thepieterdc** [comment]
@YannCebron there seems to be a bug with the verifier on your side though, it seems to execute an exponential amount of verifications.

Example:

```java -jar verifier.jar plugin.zip /ide1``` executes 1 verification

```java -jar verifier.jar plugin.zip /ide1 /ide2``` executes 4 verifications (both run twice)

```java -jar verifier.jar plugin.zip /ide1 /ide2 /ide3``` executes 9 verifications (all run 3 times)

**Comment by YannCebron** [comment]
@serejke ^^ ?

**Comment by thepieterdc** [comment]
@YannCebron @serejke log of one of my plugins using this action (I have enabled `set -euxo` to get this output):

```
2020-02-29T00:55:49.7165110Z Running verification...
2020-02-29T00:55:49.7165758Z + echo Running verification...
2020-02-29T00:55:49.7165967Z + verification_log=/tmp/verification.log
2020-02-29T00:55:49.7169164Z + java -jar /verifier.jar check-plugin /github/workspace/build/distributions/dodona-plugin-jetbrains-2.0.2-SNAPSHOT.zip /ides/ideaIU-181.5684.4 /ides/ideaIU-2019.3.3 /ides/ideaIU-LATEST-EAP-SNAPSHOT
2020-02-29T00:56:40.9865689Z Verification reports directory: verification-2020-02-29 at 00.55.50
2020-02-29T00:56:40.9866415Z 2020-02-29T00:55:51 [main] INFO  verification - Reading IDE /ides/ideaIU-181.5684.4
2020-02-29T00:56:40.9866867Z 2020-02-29T00:55:54 [main] INFO  verification - Reading IDE /ides/ideaIU-2019.3.3
2020-02-29T00:56:40.9867315Z 2020-02-29T00:55:56 [main] INFO  verification - Reading IDE /ides/ideaIU-LATEST-EAP-SNAPSHOT
2020-02-29T00:56:40.9867939Z 2020-02-29T00:55:58 [main] INFO  verification - Reading plugin to check from /github/workspace/build/distributions/dodona-plugin-jetbrains-2.0.2-SNAPSHOT.zip
2020-02-29T00:56:40.9868441Z 2020-02-29T00:55:58 [main] INFO  verification - Reading plugin to check from /github/workspace/build/distributions/dodona-plugin-jetbrains-2.0.2-SNAPSHOT.zip
2020-02-29T00:56:40.9868933Z 2020-02-29T00:55:58 [main] INFO  verification - Reading plugin to check from /github/workspace/build/distributions/dodona-plugin-jetbrains-2.0.2-SNAPSHOT.zip
2020-02-29T00:56:40.9869943Z 2020-02-29T00:55:59 [main] INFO  verification - Task check-plugin parameters:
2020-02-29T00:56:40.9870139Z Scheduled verifications (9):
2020-02-29T00:56:40.9871433Z be.ugent.piedcler.dodona:2.0.2-SNAPSHOT against IU-181.5684.4, be.ugent.piedcler.dodona:2.0.2-SNAPSHOT against IU-181.5684.4, be.ugent.piedcler.dodona:2.0.2-SNAPSHOT against IU-181.5684.4, be.ugent.piedcler.dodona:2.0.2-SNAPSHOT against IU-193.6494.35, be.ugent.piedcler.dodona:2.0.2-SNAPSHOT against IU-193.6494.35, be.ugent.piedcler.dodona:2.0.2-SNAPSHOT against IU-193.6494.35, be.ugent.piedcler.dodona:2.0.2-SNAPSHOT against IU-201.5985.32, be.ugent.piedcler.dodona:2.0.2-SNAPSHOT against IU-201.5985.32, be.ugent.piedcler.dodona:2.0.2-SNAPSHOT against IU-201.5985.32
2020-02-29T00:56:40.9871597Z 
2020-02-29T00:56:40.9872066Z 2020-02-29T00:56:33 [main] INFO  verification - Finished 1 of 9 verifications (in 34.0 s): IU-193.6494.35 against be.ugent.piedcler.dodona:2.0.2-SNAPSHOT: Compatible
2020-02-29T00:56:40.9872569Z 2020-02-29T00:56:34 [main] INFO  verification - Finished 2 of 9 verifications (in 34.9 s): IU-181.5684.4 against be.ugent.piedcler.dodona:2.0.2-SNAPSHOT: 9 compatibility problems
2020-02-29T00:56:40.9873054Z 2020-02-29T00:56:34 [main] INFO  verification - Finished 3 of 9 verifications (in 35.0 s): IU-181.5684.4 against be.ugent.piedcler.dodona:2.0.2-SNAPSHOT: 9 compatibility problems
2020-02-29T00:56:40.9873530Z 2020-02-29T00:56:34 [main] INFO  verification - Finished 4 of 9 verifications (in 35.0 s): IU-181.5684.4 against be.ugent.piedcler.dodona:2.0.2-SNAPSHOT: 9 compatibility problems
2020-02-29T00:56:40.9873993Z 2020-02-29T00:56:37 [main] INFO  verification - Finished 5 of 9 verifications (in 3.3 s): IU-193.6494.35 against be.ugent.piedcler.dodona:2.0.2-SNAPSHOT: Compatible
2020-02-29T00:56:40.9874455Z 2020-02-29T00:56:37 [main] INFO  verification - Finished 6 of 9 verifications (in 4.2 s): IU-193.6494.35 against be.ugent.piedcler.dodona:2.0.2-SNAPSHOT: Compatible
2020-02-29T00:56:40.9874953Z 2020-02-29T00:56:40 [main] INFO  verification - Finished 7 of 9 verifications (in 5.6 s): IU-201.5985.32 against be.ugent.piedcler.dodona:2.0.2-SNAPSHOT: Compatible. 3 usages of deprecated API
2020-02-29T00:56:40.9875498Z 2020-02-29T00:56:40 [main] INFO  verification - Finished 8 of 9 verifications (in 5.6 s): IU-201.5985.32 against be.ugent.piedcler.dodona:2.0.2-SNAPSHOT: Compatible. 3 usages of deprecated API
2020-02-29T00:56:40.9875980Z 2020-02-29T00:56:40 [main] INFO  verification - Finished 9 of 9 verifications (in 2.4 s): IU-201.5985.32 against be.ugent.piedcler.dodona:2.0.2-SNAPSHOT: Compatible. 3 usages of deprecated API
```

**Comment by serejke** [comment]
Oh, I apologize for not replying earlier: missed this thread completely in my GH notifications box...
This issue has been fixed in Plugin Verifier version [1.236](https://github.com/JetBrains/intellij-plugin-verifier/releases/tag/v1.236)

**Comment by thepieterdc** [comment]
> Oh, I apologize for not replying earlier: missed this thread completely in my GH notifications box...
> This issue has been fixed in Plugin Verifier version [1.236](https://github.com/JetBrains/intellij-plugin-verifier/releases/tag/v1.236)

Thanks alot! :)

**Pull request merged**
